name: Generate Podcast Feeds #name of podcast
on: [push] #when the action needs to run-when someone pushes code to main 
#execute actions
jobs: 
  build: #create a job called build
    runs-on: ubuntu-latest   #runs on specific type of machine
    steps: #series of steps
      -name: Checkout Repo
       uses: actions/checkout@v3
      -name: Setup Python  #setting up python in the machine
       uses: actions/setup-python@v4
       with: #along with the version
         python-version: '3.10'
      -name: Install dependencies
       run: |  #multi line commands
         python -m pip install --upgrade pip
         pip install pyyaml
      -name: Run feed generator
       run: python feed.py
      -name: Push repo
       run: |
         git config user.name github-actions
         git config user.email  github-actions@github.com
         git add .
         git commit -m "Modified feed"
         git push
